x = linspace(0, 20, 100);
eps = 1e-10;
inc = 100;
MaxIter = 100;

funcs = {
    @exp "e \^ x"; ...
    @(x) 10 .* x.^ 4 -  x .^ 3 - 15 * x .^2 + 10 .* x - 10, "10 * x \^ 4 -  x \^ 3 - 15 * x \^ 2 + 10 * x - 10";...
    @atan, "arctg(x)";...
    @sin, "sin(x)";...
    @(x) x ./(1.2 - sin(x)), "x /(1.2 - sin(x))";...
    @(x) x .^ atan(x), "x \^ arctg(x) "; ...
    @(x) x .^ 2, "x \^ 2"; ...
    @(x) sin(x .^2), "sin(x^2)"; ...
    };
n = length(funcs);
res = cell(length(funcs), 3);
for i = 1:n
    fprintf("Doing %s\n", funcs{i, 2});
    res(i, :) = {
        funcs(i, 2), ...
        findNOpt(x, funcs{i, 1}, inc, eps, MaxIter) ...
        findNEq(x, funcs{i, 1}, inc, eps, MaxIter) ...
        };
end

printResult(res);

 
